# Generated by Django 4.1 on 2024-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(blank=True, max_length=100, null=True)),
                ('claim_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('request_from', models.CharField(blank=True, max_length=100, null=True)),
                ('req_date', models.DateField()),
                ('current_date', models.DateField()),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('claim_date', models.DateField()),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=100, null=True)),
                ('cbn', models.CharField(blank=True, max_length=100, null=True)),
                ('hporder', models.CharField(blank=True, max_length=100, null=True)),
                ('recieved_partno', models.CharField(blank=True, max_length=100, null=True)),
                ('claimed_partno', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField()),
                ('packid', models.CharField(blank=True, max_length=100, null=True)),
                ('boxid', models.CharField(blank=True, max_length=100, null=True)),
                ('serialno', models.CharField(blank=True, max_length=100, null=True)),
                ('unitprice', models.FloatField()),
                ('totalamount', models.FloatField()),
                ('hpinvno', models.CharField(blank=True, max_length=100, null=True)),
                ('redington_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('eci_date', models.DateField()),
                ('call_iddate', models.DateField()),
                ('rr', models.CharField(blank=True, max_length=100, null=True)),
                ('customercm_callid', models.CharField(blank=True, max_length=100, null=True)),
                ('dhlawb_forwardercode', models.CharField(blank=True, max_length=100, null=True)),
                ('rpo', models.IntegerField()),
                ('rpo_date', models.DateField()),
                ('grn_date', models.DateField()),
                ('hpcn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('hpcn_date', models.DateField()),
                ('hpcn_value', models.CharField(blank=True, max_length=100, null=True)),
                ('ca', models.CharField(blank=True, max_length=100, null=True)),
                ('aging_days', models.IntegerField()),
                ('claims_status', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_claimsstatus', models.CharField(blank=True, max_length=100, null=True)),
                ('originator', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'ClaimsTracker',
            },
        ),
    ]
