# Generated by Django 4.1 on 2024-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0002_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='call_iddate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='eci_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='grn_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
