# Generated by Django 4.1 on 2024-06-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0003_alter_tracker_call_iddate_alter_tracker_eci_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='claim_type',
            new_name='claimtype',
        ),
    ]
