# Generated by Django 4.1 on 2024-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0006_additionalclaimsstatus_category_claimsstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
