# Generated by Django 4.1 on 2024-06-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0007_alter_tracker_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='rpo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='totalamount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='unitprice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
