# Generated by Django 4.1 on 2024-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0008_alter_tracker_rpo_alter_tracker_totalamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='aging_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
