# Generated by Django 4.1 on 2024-06-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0010_claimstracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalClaimsstatus',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Claimsstatus',
        ),
        migrations.DeleteModel(
            name='Originator',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='RequestFrom',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
        migrations.AlterModelOptions(
            name='claimstracker',
            options={'verbose_name_plural': 'ClaimsTracker'},
        ),
    ]
