# Generated by Django 4.1 on 2024-06-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0012_additionalclaimsstatus_category_claimsstatus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Divisons',
            new_name='Divisions',
        ),
        migrations.RenameField(
            model_name='divisions',
            old_name='Divisons',
            new_name='Divisions',
        ),
    ]
