# Generated by Django 4.1 on 2024-06-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0013_rename_divisons_divisions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimstracker',
            name='Ageingdays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimstracker',
            name='Qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
