# Generated by Django 4.1 on 2024-06-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0015_alter_claimstracker_ageingdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimstracker',
            name='SellUnitPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='claimstracker',
            name='TotalSellPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
