# Generated by Django 4.1 on 2024-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0016_alter_claimstracker_sellunitprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimstracker',
            name='SellUnitPrice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claimstracker',
            name='TotalSellPrice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
