# Generated by Django 4.1 on 2024-07-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GanesanTeam', '0018_alter_claimstracker_ageingdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimstracker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
